Repository moneymanagerex/moneymanagerex, pull requests merged in 2018-08, with the labels that each got.

#1756 fix(snapstore): add workaround to deploy to snapstore from travis
  .travis.yml
Labels: linux

#1759 feat(docker): build package for Raspberry Pi Raspbian
  .travis.yml
  CMakeLists.txt
  README.md
  dockers/debian.stretch.armhf/Dockerfile
  util/toolchain-linux-armhf.cmake
Labels: enhancement, linux

#1761 fix(travis): fix deployment
  .travis.yml
Labels: bug

#1755 fix(webapp.#935): use libcurl to send POST data so that HTTPS can be suppo…
  src/maincurrencydialog.cpp
  src/mmex.cpp
  src/stockdialog.cpp
  src/util.cpp
  src/util.h
  src/webapp.cpp
  src/wizard_update.cpp
Labels: enhancement

#1765 Enhancement: change exit hotkey to Ctrl-Q on Linux
  src/mmframe.cpp
Labels: linux

#1772 fix(#1771): don't overwrite with the same value
  src/wizard_update.cpp
Labels: bug

#1781 fix(cashflow): don't crash on an account without transactions
  src/reports/cashflow.cpp
Labels: bug, reports

#1787 fix(l10n): update pl translation
  po/pl.po
  src/currencydialog.cpp
Labels: i18n
