Repository moneymanagerex/moneymanagerex, pull requests merged in 2018-05, with the labels that each got.

#1598 fix(#1595): separate class for custom data
  src/CMakeLists.txt
  src/mmcheckingpanel.cpp
  src/mmcustomdata.cpp
  src/mmcustomdata.h
  src/mmframe.cpp
  src/model/Model_CustomFieldData.cpp
  src/model/Model_CustomFieldData.h
  src/transdialog.cpp
  src/transdialog.h
Labels: fixed

#1618 chore(#1585): show valued fields
  src/mmcustomdata.cpp
  src/mmcustomdata.h
  src/transdialog.cpp
Labels: enhancement

#1622 feat(Travis): generate nightly builds and publish on GitHub Releases
  .travis.yml
Labels: feature

#1650 fix(AppVeyor): add force_update for nightly builds
  .appveyor.yml
Labels: bug

#1653 New badges in README.md
  README.md
Labels: doc, enhancement, linux, mac, on hold

#1656 fix(#1642): settings
  src/filtertransdialog.cpp
  src/filtertransdialog.h
Labels: fixed

#1657 fix(#1656): montly grouping data
  src/reports/summary.cpp
Labels: fixed

#1660 fix(#1658): wxRadioBox selection
  src/filtertransdialog.cpp
Labels: fixed

#1661 fix(#1624): sorting
  src/mmcheckingpanel.cpp
Labels: fixed

#1669 fix(#1667): correct table name from db v7
  src/dbupgrade.cpp
Labels: fixed

#1668 fix(#1663): event id
  src/transdialog.cpp
  src/transdialog.h
Labels: fixed

#1681 feat(CMake): use system-wide rapidjson if available
  3rd/CMakeLists.txt
  dockers/archlinux/Dockerfile
  dockers/debian.buster.x86/Dockerfile
  dockers/debian.buster/Dockerfile
  dockers/debian.jessie.x86/Dockerfile
  dockers/debian.jessie/Dockerfile
  dockers/debian.stretch.x86/Dockerfile
  dockers/debian.stretch/Dockerfile
  dockers/el.6/Dockerfile
  dockers/el.7/Dockerfile
  dockers/fedora.24/Dockerfile
  dockers/fedora.25/Dockerfile
  dockers/fedora.26/Dockerfile
  dockers/fedora/Dockerfile
  dockers/linuxmint.serena/Dockerfile
  dockers/linuxmint.sonya/Dockerfile
  dockers/linuxmint.sylvia.x86/Dockerfile
  dockers/linuxmint.sylvia/Dockerfile
  dockers/linuxmint.tara.x86/Dockerfile
  dockers/linuxmint.tara/Dockerfile
  dockers/opensuse.42.1/Dockerfile
  dockers/opensuse.42.2/Dockerfile
  dockers/opensuse.42.3/Dockerfile
  dockers/opensuse/Dockerfile
  dockers/slackware.14.2/Dockerfile
  dockers/ubuntu.artful.x86/Dockerfile
  dockers/ubuntu.artful/Dockerfile
  dockers/ubuntu.bionic.x86/Dockerfile
  dockers/ubuntu.bionic/Dockerfile
  dockers/ubuntu.xenial.x86/Dockerfile
  dockers/ubuntu.xenial/Dockerfile
  dockers/ubuntu.zesty.x86/Dockerfile
  dockers/ubuntu.zesty/Dockerfile
Labels: enhancement

#1682 fix(cashflow): fix SEGFAULT in cashflow report
  src/reports/cashflow.cpp
Labels: bug

#1685 feat(authors): add script to list commit authors with years
  .mailmap
  util/list-authors.sh
Labels: doc

#1686 fix(#1681): RapidJSON v1.1 is required to use Pointer operations
  3rd/CMakeLists.txt
  dockers/fedora.24/Dockerfile
Labels: bug

#1688 refactor(myusage): redesign My Usage report
  CMakeLists.txt
  src/option.cpp
  src/reports/myusage.cpp
Labels: bug, enhancement, i18n
