Repository moneymanagerex/moneymanagerex, pull requests merged in 2018-03, with the labels that each got.

#1457 Revert "Merge pull request #1359 from stephengroat/brew-bundle"
  .travis.yml
  util/Brewfile
Labels: bug, mac

#1495 Translations
  po/pl.po
  po/ru.po
  src/aboutdialog.cpp
  src/appstartdialog.cpp
  src/constants.cpp
  src/constants.h
  src/general_report_manager.cpp
  src/import_export/qif_import_gui.cpp
  src/import_export/univcsvdialog.cpp
  src/mmcheckingpanel.cpp
  src/mmcheckingpanel.h
  src/mmex.cpp
  src/mmframe.cpp
  src/mmhelppanel.cpp
  src/mmhomepagepanel.cpp
  src/mmreportspanel.cpp
  src/model/Model_Checking.cpp
  src/model/Model_Currency.cpp
  src/model/Model_Currency.h
  src/model/Model_Report.cpp
  src/option.cpp
  src/optionsettingsattachment.cpp
  src/optionsettingsgeneral.cpp
  src/optionsettingsview.cpp
  src/paths.cpp
  src/paths.h
  src/reports/cashflow.cpp
  src/reports/htmlbuilder.cpp
  src/reports/summarystocks.cpp
  src/stockdialog.cpp
  src/transdialog.cpp
  src/util.cpp
  src/util.h
  src/webserver.cpp
  src/wizard_newaccount.cpp
  util/update-po-files.sh
Labels: bug, i18n

#1494 feat(icons): replace LED_OFF icon with CURRATES in stock dialogs
  src/images_list.cpp
  src/images_list.h
  src/stockdialog.cpp
  src/stockspanel.cpp
Labels: enhancement

#1499 chore(AppVeyor): update wxWidgets to 3.1.1 for windows builds
  .appveyor.yml
Labels: win

#1509 fix(#1495): ignore locale setting and force C number formatting where…
  src/currencydialog.cpp
  src/import_export/export.cpp
  src/mmhomepagepanel.cpp
  src/reports/forecast.cpp
  src/reports/htmlbuilder.cpp
  src/transdialog.cpp
Labels: bug, i18n

#1518 fix(docker): use lua5.2 for Ubuntu Jessie
  dockers/debian.jessie.x86/Dockerfile
  dockers/debian.jessie/Dockerfile
Labels: linux

#1519 doc(rapidjson): RapidJSON mentioned in few places
  3rd/CMakeLists.txt
  README.md
  src/CMakeLists.txt
  src/constants.cpp
Labels: doc

#1523 fix(i18n): Polish translation update
  po/pl.po
Labels: i18n

#1525 fix(Model_Report): case structure
  src/model/Model_Report.cpp
Labels: bug
