Repository moneymanagerex/moneymanagerex, pull requests merged in 2018-11, with the labels that each got.

#1873 fix(DB_upgrade): revert changes from 9f8f9b6
  src/db/DB_Upgrade.h
Labels: bug

#1874 chore(travis): update to the latest image
  .travis.yml
Labels: enhancement

#1879 fix(#1878): Replace unsupported comment in json with simple field.
  CMakeSettings.json
Labels: bug, win
