Repository moneymanagerex/moneymanagerex, pull requests merged in 2018-04, with the labels that each got.

#1532 chore(libcurl): update Windows builds to latest libcurl 7.59.0
  .appveyor.yml
Labels: win

#1554 fix(#1553): update BUILD.md after #1547
  BUILD.md
Labels: doc, win

#1555 refactor(cmake): don't require C99 under MSVC for SQLite3 security ext
  .appveyor.yml
  3rd/CMakeLists.txt
  BUILD.md
  util/MSVC-C.cmake.patch
Labels: enhancement

#1569 fix(#1566): clean GUI before ShutdownDatabase() call
  src/constants.cpp
  src/mmframe.cpp
  src/mmframe.h
  src/model/Model_Infotable.cpp
Labels: bug, enhancement

#1572 fix(#1569): fix typo
  src/model/Model_Infotable.cpp
Labels: bug

#1573 feat(encryption): autodetect encrypted databases
  src/dbwrapper.cpp
  src/mmTips.h
  src/mmframe.cpp
  src/mmframe.h
  src/optionsettingsattachment.cpp
Labels: feature

#1576 fix(#1573) downgrde cipher to aes128 previously used
  3rd/CMakeLists.txt
Labels: bug

#1580 fix(#1089) refactoring
  resources/custom_fields_png.h
  src/CMakeLists.txt
  src/customfielddialog.cpp
  src/customfielddialog.h
  src/customfieldeditdialog.cpp
  src/customfieldlistdialog.cpp
  src/customfieldlistdialog.h
  src/images_list.cpp
  src/images_list.h
  src/mmframe.cpp
  src/mmframe.h
  src/model/Model_CustomField.cpp
  src/transdialog.cpp
  src/transdialog.h
Labels: feature

#1600 fix(#1539): fix mmCalculator input and output formatting
  src/CMakeLists.txt
  src/accountdialog.h
  src/assetdialog.cpp
  src/billsdepositsdialog.h
  src/budgetentrydialog.h
  src/currencydialog.cpp
  src/customfieldeditdialog.cpp
  src/filtertransdialog.h
  src/import_export/qif_import_gui.cpp
  src/maincurrencydialog.cpp
  src/mmCalculator.cpp
  src/mmCalculator.h
  src/mmTextCtrl.cpp
  src/mmTextCtrl.h
  src/mmtextctrl.h
  src/model/Model_Currency.cpp
  src/model/Model_Currency.h
  src/sharetransactiondialog.cpp
  src/splitdetailsdialog.h
  src/stockdialog.cpp
  src/transactionsupdatedialog.cpp
  src/transdialog.cpp
  src/usertransactionpanel.h
  src/util.cpp
Labels: bug

#1608 fix(i18n): update po files and small fixes
  po/ab.po
  po/ar.po
  po/bg.po
  po/ca.po
  po/cs.po
  po/de.po
  po/el.po
  po/en_GB.po
  po/es.po
  po/fa.po
  po/fi.po
  po/fr.po
  po/he.po
  po/hi.po
  po/hr.po
  po/hu.po
  po/id.po
  po/it.po
  po/ja.po
  po/ko.po
  po/lt.po
  po/lv.po
  po/ml.po
  po/mmex.pot
  po/my.po
  po/nb.po
  po/nl_BE.po
  po/nl_NL.po
  po/pl.po
  po/pt_BR.po
  po/pt_PT.po
  po/ro.po
  po/ru.po
  po/sh.po
  po/sk.po
  po/sl.po
  po/sq.po
  po/sr.po
  po/sv.po
  po/ta.po
  po/th.po
  po/tr.po
  po/uk.po
  po/vi.po
  po/zh_CN.po
  po/zh_TW.po
  src/attachmentdialog.cpp
  src/general_report_manager.cpp
  src/import_export/qif_export.cpp
  src/import_export/qif_import_gui.cpp
  src/import_export/univcsvdialog.cpp
  src/mmframe.cpp
  src/stockdialog.cpp
Labels: bug, i18n

#1609 fix(custom): fix custom fields manager menus
  src/mmframe.cpp
  src/mmframe.h
Labels: bug
