Repository moneymanagerex/moneymanagerex, pull requests merged in 2018-10, with the labels that each got.

#1830 fix(docker): fix archlinux image
  dockers/archlinux/Dockerfile
Labels: linux

#1824 refactor(travis): build only one Mac package
  .gitignore
  .travis.yml
  CMakeLists.txt
  README.md
  resources/dmg-DS_Store
Labels: enhancement, help wanted, mac

#1836 fix(cmake): use patched FindwxWidgets.cmake module
  CMakeLists.txt
  util/FindwxWidgets.cmake
Labels: bug

#1814 Update Arabic translation
  po/ar.po
Labels: i18n

#1840 fix(checkUpdates): workaround for GitHub API rate limit exceeded error
  src/wizard_update.cpp
Labels: bug

#1843 Fixing many German translations
  po/de.po
Labels: i18n

#1845 style(cmake): improve cmake scripts
  3rd/CMakeLists.txt
  CMakeLists.txt
Labels: enhancement

#1847 fix(#1846): define MMEX_WEBSERVER for optiondialog.cpp
  src/CMakeLists.txt
Labels: bug

#1851 refactor(SendStatsThread): replace mongoose with libcurl
  src/CMakeLists.txt
  src/constants.cpp
  src/constants.h
  src/model/Model_Usage.cpp
  src/util.cpp
  src/util.h
Labels: enhancement

#1837 fix(#1777): filter statuses for transfers
  src/filtertransdialog.cpp
  src/filtertransdialog.h
  src/model/Model_Checking.cpp
Labels: enhancement
