Repository moneymanagerex/moneymanagerex, pull requests merged in 2019-04, with the labels that each got.

#2139 feat(i18n): add some wxPLURAL to sources
  src/billsdepositspanel.cpp
  src/customfieldlistdialog.cpp
  src/general_report_manager.cpp
  src/import_export/qif_import_gui.cpp
  src/mmhomepagepanel.cpp
  src/reports/cashflow.cpp
Labels: enhancement, i18n

#2143 grrrrrrrr...
  src/reports/cashflow.cpp
Labels: i18n

#2144 fix(#2142) simplification
  src/billsdepositspanel.cpp
  src/billsdepositspanel.h
  src/mmhomepagepanel.cpp
  src/model/Model_Billsdeposits.cpp
  src/model/Model_Billsdeposits.h
Labels: enhancement

#2155 fix(README): update broken img.shields.io badges
  README.md
Labels: doc

#2160 fix(#2157): calculate WeekDayNameMaxSize
  src/transdialog.cpp
Labels: bug

#2159 fix(#1947): report errors for FindwxWidgets.cmake
  util/FindwxWidgets.cmake
Labels: enhancement, linux, mac

#2161 fix(#2156): fix TABLE_CELL_SPAN
  src/reports/htmlbuilder.cpp
  src/reports/htmlbuilder.h
Labels: bug, reports

#2162 feat(htmlbuilder): always print curr symbol
  src/reports/htmlbuilder.cpp
Labels: enhancement, reports

#2163 Fix reports panel layout
  resources/home_page.htt
  src/general_report_manager.cpp
  src/mmreportspanel.cpp
  src/reports/budgetingperf.cpp
  src/reports/categexp.cpp
  src/reports/reportbase.cpp
  src/reports/summary.cpp
  src/reports/transactions.cpp
Labels: enhancement, reports
