Repository moneymanagerex/moneymanagerex, pull requests merged in 2019-02, with the labels that each got.

#1982 fix Polish translations
  po/pl_PL.po
  util/update-po-files.sh
Labels: i18n

#1987 fix(l10n): remove empty and wrong english translations
  po/en_GB.po
  po/en_US.po
Labels: bug, i18n

#1995 fix(#1933): new help files structure
  docs/budget.html
  docs/de/budget.html
  docs/de/grm.html
  docs/de/index.html
  docs/de/stocks_and_shares.html
  docs/en/assetsGRM_.gif
  docs/en/budget.html
  docs/en/budget_editor.png
  docs/en/budget_entry_details.png
  docs/en/budget_grid.png
  docs/en/grm.gif
  docs/en/grm.html
  docs/en/grm_custom_date.png
  docs/en/grm_toolbar.png
  docs/en/index.html
  docs/en/mmex_concept.png
  docs/en/mmex_db_structure.png
  docs/en/stock_shares_new_shares.png
  docs/en/stock_shares_new_stock.png
  docs/en/stock_shares_portfolio.png
  docs/en/stock_shares_share_account.png
  docs/en/stock_shares_view_transactions.png
  docs/en/stocks_and_shares.html
  docs/es/budget.html
  docs/es/grm.html
  docs/es/index.html
  docs/es/stocks_and_shares.html
  docs/fr/budget.html
  docs/fr/grm.html
  docs/fr/index.html
  docs/fr/mmex_concept.png
  docs/fr/stocks_and_shares.html
  docs/grm.html
  docs/hu/budget.html
  docs/hu/grm.html
  docs/hu/index.html
  docs/hu/mmex_concept.png
  docs/hu/stocks_and_shares.html
  docs/index.html
  docs/it/budget.html
  docs/it/grm.html
  docs/it/index.html
  docs/it/stocks_and_shares.html
  docs/pl/btn_donateCC_LG.gif
  docs/pl/budget.html
  docs/pl/budget_editor.png
  docs/pl/budget_entry_details.png
  docs/pl/budget_grid.png
  docs/pl/grm.html
  docs/pl/index.html
  docs/pl/mmex_concept.png
  docs/pl/stocks_and_shares.html
  docs/ru/budget.html
  docs/ru/grm.html
  docs/ru/grm_custom_date.png
  docs/ru/index.html
  docs/ru/mmex_concept.png
  docs/ru/stocks_and_shares.html
  docs/stocks_and_shares.html
Labels: enhancement

#2007 fix(i10n): update
  po/fr_FR.po
Labels: i18n

#2012 Fix user manual
  CMakeLists.txt
  docs/budget.html
  docs/de/budget.html
  docs/de/grm.html
  docs/de/index.html
  docs/de/stocks_and_shares.html
  docs/en/btn_donateCC_LG.gif
  docs/en/budget.html
  docs/en/grm.html
  docs/en/index.html
  docs/en/stocks_and_shares.html
  docs/es/budget.html
  docs/es/grm.html
  docs/es/index.html
  docs/es/stocks_and_shares.html
  docs/fr/budget.html
  docs/fr/grm.html
  docs/fr/index.html
  docs/fr/stocks_and_shares.html
  docs/grm.html
  docs/hu/budget.html
  docs/hu/grm.html
  docs/hu/index.html
  docs/hu/stocks_and_shares.html
  docs/it/budget.html
  docs/it/grm.html
  docs/it/index.html
  docs/it/stocks_and_shares.html
  docs/js/get_param.js
  docs/js/lang_menu.js
  docs/js/toc.js
  docs/manual.css
  docs/pl/budget.html
  docs/pl/grm.html
  docs/pl/index.html
  docs/pl/stocks_and_shares.html
  docs/ru/budget.html
  docs/ru/grm.html
  docs/ru/index.html
  docs/ru/stocks_and_shares.html
  docs/stocks_and_shares.html
Labels: doc, enhancement, i18n

#2020 Shorter dynamic table of contents in user manual
  docs/de/index.html
  docs/en/grm.html
  docs/en/index.html
  docs/es/index.html
  docs/fr/index.html
  docs/hu/index.html
  docs/it/index.html
  docs/js/back_to_top.js
  docs/js/lang_menu.js
  docs/js/toc.js
  docs/manual.css
  docs/pl/index.html
  docs/ru/grm.html
  docs/ru/index.html
Labels: doc, enhancement

#2021 chore(appveyor): update libcurl to 7.64 for windows packages
  .appveyor.yml
Labels: win

#1936 fix(#1697): update index.html with new features
  docs/en/index.html
Labels: doc, enhancement

#2024 fix(#1980): payee pie chart colors
  src/reports/htmlbuilder.cpp
  src/reports/htmlbuilder.h
  src/reports/payee.cpp
Labels: bug, reports

#2035 fix(docker): archlinux repo moved
  dockers/archlinux/Dockerfile
Labels: enhancement, linux

#2038 chore(doc): update INSTALL.md
  INSTALL.md
Labels: doc, enhancement, linux

#2041 fix(#1990): crowdin menu added
  po/mmex.pot
  resources/globe_png.h
  src/constants.cpp
  src/constants.h
  src/images_list.cpp
  src/images_list.h
  src/mmframe.cpp
  src/mmframe.h
Labels: enhancement

#2049 fix(#2044): add transaction notes as tooltip
  src/mmhomepagepanel.cpp
Labels: enhancement

#2039 feat(snap): build Linux snap packages
  .editorconfig
  .gitattributes
  .gitignore
  .snapcraft.yaml
  INSTALL.Ubuntu.md
Labels: doc, enhancement, linux

#2052 fix(#2041): fix invalid menu item type
  src/mmframe.cpp
Labels: bug

#2056 fix(#2043): matches and empty notes and number
  src/filtertransdialog.cpp
Labels: enhancement

#2058 fix(l10n): update
  po/bg_BG.po
  po/cs_CZ.po
  po/de_DE.po
  po/es_ES.po
  po/fr_FR.po
  po/he_IL.po
  po/hu_HU.po
  po/it_IT.po
  po/ja_JP.po
  po/lt_LT.po
  po/mmex.pot
  po/nl_NL.po
  po/pl_PL.po
  po/pt_BR.po
  po/ru_RU.po
  po/sk_SK.po
  po/sq_AL.po
  po/tr_TR.po
  po/zh_CN.po
Labels: i18n

#2053 fix(#2025): detailed info when translation is missing
  src/mmex.cpp
Labels: enhancement, i18n

#2064 fix(#2063): next previous period single date
  src/mmreportspanel.cpp
Labels: fixed

#2067 fix(#2065): bar chart added
  src/reports/categovertimeperf.cpp
  src/reports/htmlbuilder.cpp
  src/reports/htmlbuilder.h
  src/reports/incexpenses.cpp
  src/util.h
Labels: enhancement, reports
